version: 0.0
os: windows
files:
 - source: .\_build
   destination: C:\Users\Administrator\VCS
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
