name: Local runner test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  BuildApplicationDocker:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: pwsh
    env:
      Solution_Name: ApplicationSettings.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path:  GitWorkflowRun/ApplicationSettings/ApplicationSettings.csproj            
      Wap_Project_Directory: GitWorkflowRun/ApplicationSettings/
      Wap_Project_Path: GitWorkflowRun/ApplicationSettings/Artifacts/ 
    steps:
      - uses: actions/checkout@v2
       
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe'

      - name: Restore Packages
        run: nuget restore $env:Solution_Name
        
      - name: Build and Publish Web App
        run: msbuild.exe $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
        
    
