name: Local runner test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  BuildApplicationDocker:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: pwsh
    env:
      Solution_Name: ApplicationSettings.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path:  GitWorkflowRun/ApplicationSettings/ApplicationSettings.csproj            
      Wap_Project_Directory: GitWorkflowRun/ApplicationSettings/
      Wap_Project_Path: GitWorkflowRun/ApplicationSettings/Artifacts/ 
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
       
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Restore NuGet Packages
        run: nuget restore SimpleFrameworkApp.sln
      
      - name: Build and Publish Web App
        run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
        
    
