name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: shailu0287/docker-github-runner-win3
    steps:
         - name: Log the parent container node version
           run: |
             echo 'running'
