
name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:



    runs-on: self-hosted 
    env:
      Solution_Name: ApplicationSettings.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path:  GitWorkflowRun/ApplicationSettings/ApplicationSettings.csproj            
      Wap_Project_Directory: GitWorkflowRun/ApplicationSettings/
      Wap_Project_Path: GitWorkflowRun/ApplicationSettings/Artifacts/                  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    
 
  
    
    - name: Create Build Directory
      run: mkdir _build
  
    - name: Restore Packages
      run: nuget restore $env:Solution_Name
      
    - name: Build the application
      run: |
            msbuild.exe $env:Solution_Name /p:DeployOnBuild=true /p:OutputPath="../_build" /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" 
            
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WindowFormDevOpsBundle
        path: "./_build" 
     

